locale: "en-US"
title: AHerforth # Title of your site
url: "http://aleksion.github.io" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog/
google_analytics_key: "UA-92328257-1"

# Default description in social shares for the jekyll-seo-tag gem
description: > # this means to ignore newlines until "baseurl:"
  Aleksander Herforth Rendtslev's personal blog. This will explain my entrepreneurial ventures
  as well as my coding endeavors. 

# Author details for the jekyll-seo-tag gem
author:
  name: Aleksander Herforth Rendtslev
  email: aleksander@rendtslev.com
  twitter: aherforth

# Social details for the jekyll-seo-tag gem
social:
  name: Aleksanders Personal Blog
  links:
    - https://github.com/comfusion/strata-reloaded-jekyll-template

permalink: pretty
excerpt_separator: <!--more-->
gems:
  - "jekyll-feed"
  - "jekyll-seo-tag"
  - "jekyll-paginate"
  - "jekyll-sitemap"

# Jekyll SEO Tag
webmaster_verifications:
  google: #UA-92328257-1
  bing: # 1234
  alexa: # 1234
  yandex: # 1234

# -----------
# CloudCannon

social_icons:
  - Facebook
  - Instagram
  - LinkedIn
  - Twitter
  - RSS
